FROM python
RUN apt-get update
RUN apt-get install -y runit
RUN pip install -v docker==2.7.0
RUN pip install elasticsearch
RUN pip install pygerrit2
RUN pip install python-gitlab
RUN pip install flask
RUN pip install flask_login
RUN pip install flask_babelex
RUN pip install flask_compress
RUN pip install pydash
RUN pip install raven
RUN pip install mysql-connector-python
RUN pip install gunicorn
RUN pip install --upgrade PyMySQL
RUN pip install --upgrade SQLAlchemy
RUN pip install flask_cors
RUN pip install flask_sqlalchemy
RUN pip install wtforms
