version: "2"
services:
  server_mysql:
    container_name: server_mysql
    image: mysql:5.7.23
    ports:
    - 3306:3306
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: server
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: apiserver
#  server_web:
#    container_name: server_web
#    build: .
#    volumes:
#      - ../../:/opt/home/
##      - /var/run/docker.sock:/var/run/docker.sock
#    working_dir: /opt/home/server
#    environment:
#      IS_DOCKER: 1
#    ports:
#      - 8080:8080
#    depends_on:
#      - server_mysql
#    entrypoint: ['bash', '-c', 'gunicorn -w 1 server:app -b 0.0.0.0:8080 --reload']

